repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: bash -c "cd car_salon_activities && pipenv run isort --check-only ."
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: bash -c "cd car_salon_activities && pipenv run black --check ."
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: bash -c "cd car_salon_activities && pipenv run flake8 ."
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: bash -c "cd car_salon_activities && pipenv run mypy ."
        language: system
        types: [python]
        pass_filenames: false
